import Header from './layout-components/Header'
import Footer from './layout-components/Footer'
import { Raleway } from 'next/font/google'
import './globals.css'
import "@fortawesome/fontawesome-svg-core/styles.css"
import { config } from "@fortawesome/fontawesome-svg-core"

config.autoAddCss = false

const raleway = Raleway({
  weight: ['300', '400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})
 
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
 
export default function RootLayout({ children }) {
  return (
    <html lang="en" className={raleway.className}>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
